import {
  AddToBag,
  ArticleSlider,
  CardWallet,
  ContactUs,
  CreateAccount,
  FurFriends,
  HomePage,
  HotelBooking,
  ImageCarousel,
  ImagePreview,
  Invoices,
  JobBoard,
  LeaderBoards,
  MeetingSchedule,
  Messages,
  MobileNavigation,
  MovieTicket,
  MusicEvents,
  Notifications,
  PasswordGenerator,
  PlayList,
  PricingPlans,
  ProfileCard,
  Recipe,
  RestaurantReservation,
  ShoppingList,
  SignUp,
  TaskBoard,
  UploadImage,
  UserProfile,
  VideoPlayer,
} from "./challenges/solutions";

export const challenges = [
  { day: 1, title: "Profile Card", solution: ProfileCard },
  { day: 2, title: "Add To Bag", solution: AddToBag },
  { day: 3, title: "Mobile Navigation", solution: MobileNavigation },
  { day: 4, title: "Contact Us", solution: ContactUs },
  { day: 5, title: "Recipe", solution: Recipe },
  { day: 6, title: "Image Carousel", solution: ImageCarousel },
  { day: 7, title: "Create Account", solution: CreateAccount },
  { day: 8, title: "Music events", solution: MusicEvents },
  { day: 9, title: "Password generator", solution: PasswordGenerator },
  { day: 10, title: "SignUp", solution: SignUp },
  { day: 11, title: "Hotel Booking", solution: HotelBooking },
  { day: 12, title: "Restaurant Reservation", solution: RestaurantReservation },
  { day: 13, title: "Task Board", solution: TaskBoard },
  { day: 14, title: "Shopping List", solution: ShoppingList },
  { day: 15, title: "Notifications", solution: Notifications },
  { day: 16, title: "Fur Friends", solution: FurFriends },
  { day: 17, title: "Article Slider", solution: ArticleSlider },
  { day: 18, title: "Image Preview", solution: ImagePreview },
  { day: 19, title: "Upload Photo", solution: UploadImage },
  { day: 20, title: "Card Wallet", solution: CardWallet },
  { day: 21, title: "Pricing Plans", solution: PricingPlans },
  { day: 22, title: "Messages", solution: Messages },
  { day: 23, title: "Home Page", solution: HomePage },
  { day: 24, title: "Movie Ticket", solution: MovieTicket },
  { day: 25, title: "Meeting Schedule", solution: MeetingSchedule },
  { day: 26, title: "Job Board", solution: JobBoard },
  { day: 27, title: "Leaderboards", solution: LeaderBoards },
  { day: 28, title: "Playlist", solution: PlayList },
  { day: 29, title: "Video Player", solution: VideoPlayer },
  { day: 30, title: "Invoices", solution: Invoices },
  { day: 31, title: "undefined", solution: undefined },
  { day: 32, title: "undefined", solution: undefined },
  { day: 33, title: "undefined", solution: undefined },
  { day: 34, title: "User Profile", solution: UserProfile },
];
