import {
  AddToBag,
  ContactUs,
  CreateAccount,
  FurFriends,
  HotelBooking,
  ImageCarousel,
  MobileNavigation,
  MusicEvents,
  Notifications,
  PasswordGenerator,
  ProfileCard,
  Recipe,
  RestaurantReservation,
  ShoppingList,
  SignUp,
  TaskBoard,
} from "./challenges/solutions";

export const challenges = [
  { day: 1, title: "Profile Card", solution: ProfileCard },
  { day: 2, title: "Add To Bag", solution: AddToBag },
  { day: 3, title: "Mobile Navigation", solution: MobileNavigation },
  { day: 4, title: "Contact Us", solution: ContactUs },
  { day: 5, title: "Recipe", solution: Recipe },
  { day: 6, title: "Image Carousel", solution: ImageCarousel },
  { day: 7, title: "Create Account", solution: CreateAccount },
  { day: 8, title: "Music events", solution: MusicEvents },
  { day: 9, title: "Password generator", solution: PasswordGenerator },
  { day: 10, title: "SignUp", solution: SignUp },
  { day: 11, title: "Hotel Booking", solution: HotelBooking },
  { day: 12, title: "Restaurant Reservation", solution: RestaurantReservation },
  { day: 13, title: "Task Board", solution: TaskBoard },
  { day: 14, title: "Shopping List", solution: ShoppingList },
  { day: 15, title: "Notifications", solution: Notifications },
  { day: 16, title: "Fur Friends", solution: FurFriends },
];
